# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: smokers.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'smokers.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsmokers.proto\x12\x07smokers\"<\n\x11IngredientMessage\x12\'\n\ningredient\x18\x01 \x01(\x0e\x32\x13.smokers.Ingredient\":\n\x0eIngredientList\x12(\n\x0bingredients\x18\x01 \x03(\x0e\x32\x13.smokers.Ingredient\"\x07\n\x05\x45mpty\"\x0f\n\rNotifyRequest\"!\n\x0eNotifyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x11\n\x0f\x43ontinueRequest\"\x12\n\x10\x43ontinueResponse\"K\n\x0fRegisterRequest\x12\'\n\ningredient\x18\x01 \x01(\x0e\x32\x13.smokers.Ingredient\x12\x0f\n\x07\x61\x64\x64ress\x18\x02 \x01(\t\"#\n\x10RegisterResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08*<\n\nIngredient\x12\x0b\n\x07UNKNOWN\x10\x00\x12\t\n\x05PAPER\x10\x01\x12\x0b\n\x07TOBACCO\x10\x02\x12\t\n\x05MATCH\x10\x03\x32\x8d\x02\n\x0cTableService\x12;\n\rPutIngredient\x12\x1a.smokers.IngredientMessage\x1a\x0e.smokers.Empty\x12<\n\x0eTakeIngredient\x12\x1a.smokers.IngredientMessage\x1a\x0e.smokers.Empty\x12;\n\x10\x43heckIngredients\x12\x0e.smokers.Empty\x1a\x17.smokers.IngredientList\x12\x45\n\x0eRegisterSmoker\x12\x18.smokers.RegisterRequest\x1a\x19.smokers.RegisterResponse2U\n\rDealerService\x12\x44\n\rContinueRound\x12\x18.smokers.ContinueRequest\x1a\x19.smokers.ContinueResponse2J\n\rSmokerService\x12\x39\n\x06Notify\x12\x16.smokers.NotifyRequest\x1a\x17.smokers.NotifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'smokers_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INGREDIENT']._serialized_start=362
  _globals['_INGREDIENT']._serialized_end=422
  _globals['_INGREDIENTMESSAGE']._serialized_start=26
  _globals['_INGREDIENTMESSAGE']._serialized_end=86
  _globals['_INGREDIENTLIST']._serialized_start=88
  _globals['_INGREDIENTLIST']._serialized_end=146
  _globals['_EMPTY']._serialized_start=148
  _globals['_EMPTY']._serialized_end=155
  _globals['_NOTIFYREQUEST']._serialized_start=157
  _globals['_NOTIFYREQUEST']._serialized_end=172
  _globals['_NOTIFYRESPONSE']._serialized_start=174
  _globals['_NOTIFYRESPONSE']._serialized_end=207
  _globals['_CONTINUEREQUEST']._serialized_start=209
  _globals['_CONTINUEREQUEST']._serialized_end=226
  _globals['_CONTINUERESPONSE']._serialized_start=228
  _globals['_CONTINUERESPONSE']._serialized_end=246
  _globals['_REGISTERREQUEST']._serialized_start=248
  _globals['_REGISTERREQUEST']._serialized_end=323
  _globals['_REGISTERRESPONSE']._serialized_start=325
  _globals['_REGISTERRESPONSE']._serialized_end=360
  _globals['_TABLESERVICE']._serialized_start=425
  _globals['_TABLESERVICE']._serialized_end=694
  _globals['_DEALERSERVICE']._serialized_start=696
  _globals['_DEALERSERVICE']._serialized_end=781
  _globals['_SMOKERSERVICE']._serialized_start=783
  _globals['_SMOKERSERVICE']._serialized_end=857
# @@protoc_insertion_point(module_scope)
