# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import smokers_pb2 as smokers__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in smokers_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TableServiceStub(object):
    """Service für den Tisch (Table)
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PutIngredient = channel.unary_unary(
                '/smokers.TableService/PutIngredient',
                request_serializer=smokers__pb2.IngredientMessage.SerializeToString,
                response_deserializer=smokers__pb2.Empty.FromString,
                _registered_method=True)
        self.TakeIngredient = channel.unary_unary(
                '/smokers.TableService/TakeIngredient',
                request_serializer=smokers__pb2.IngredientMessage.SerializeToString,
                response_deserializer=smokers__pb2.Empty.FromString,
                _registered_method=True)
        self.CheckIngredients = channel.unary_unary(
                '/smokers.TableService/CheckIngredients',
                request_serializer=smokers__pb2.Empty.SerializeToString,
                response_deserializer=smokers__pb2.IngredientList.FromString,
                _registered_method=True)
        self.RegisterSmoker = channel.unary_unary(
                '/smokers.TableService/RegisterSmoker',
                request_serializer=smokers__pb2.RegisterRequest.SerializeToString,
                response_deserializer=smokers__pb2.RegisterResponse.FromString,
                _registered_method=True)


class TableServiceServicer(object):
    """Service für den Tisch (Table)
    """

    def PutIngredient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TakeIngredient(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckIngredients(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterSmoker(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TableServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PutIngredient': grpc.unary_unary_rpc_method_handler(
                    servicer.PutIngredient,
                    request_deserializer=smokers__pb2.IngredientMessage.FromString,
                    response_serializer=smokers__pb2.Empty.SerializeToString,
            ),
            'TakeIngredient': grpc.unary_unary_rpc_method_handler(
                    servicer.TakeIngredient,
                    request_deserializer=smokers__pb2.IngredientMessage.FromString,
                    response_serializer=smokers__pb2.Empty.SerializeToString,
            ),
            'CheckIngredients': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckIngredients,
                    request_deserializer=smokers__pb2.Empty.FromString,
                    response_serializer=smokers__pb2.IngredientList.SerializeToString,
            ),
            'RegisterSmoker': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterSmoker,
                    request_deserializer=smokers__pb2.RegisterRequest.FromString,
                    response_serializer=smokers__pb2.RegisterResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smokers.TableService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smokers.TableService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TableService(object):
    """Service für den Tisch (Table)
    """

    @staticmethod
    def PutIngredient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smokers.TableService/PutIngredient',
            smokers__pb2.IngredientMessage.SerializeToString,
            smokers__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TakeIngredient(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smokers.TableService/TakeIngredient',
            smokers__pb2.IngredientMessage.SerializeToString,
            smokers__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckIngredients(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smokers.TableService/CheckIngredients',
            smokers__pb2.Empty.SerializeToString,
            smokers__pb2.IngredientList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterSmoker(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smokers.TableService/RegisterSmoker',
            smokers__pb2.RegisterRequest.SerializeToString,
            smokers__pb2.RegisterResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class DealerServiceStub(object):
    """Service für den Dealer
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ContinueRound = channel.unary_unary(
                '/smokers.DealerService/ContinueRound',
                request_serializer=smokers__pb2.ContinueRequest.SerializeToString,
                response_deserializer=smokers__pb2.ContinueResponse.FromString,
                _registered_method=True)


class DealerServiceServicer(object):
    """Service für den Dealer
    """

    def ContinueRound(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DealerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ContinueRound': grpc.unary_unary_rpc_method_handler(
                    servicer.ContinueRound,
                    request_deserializer=smokers__pb2.ContinueRequest.FromString,
                    response_serializer=smokers__pb2.ContinueResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smokers.DealerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smokers.DealerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DealerService(object):
    """Service für den Dealer
    """

    @staticmethod
    def ContinueRound(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smokers.DealerService/ContinueRound',
            smokers__pb2.ContinueRequest.SerializeToString,
            smokers__pb2.ContinueResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class SmokerServiceStub(object):
    """Service für den Smoker
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Notify = channel.unary_unary(
                '/smokers.SmokerService/Notify',
                request_serializer=smokers__pb2.NotifyRequest.SerializeToString,
                response_deserializer=smokers__pb2.NotifyResponse.FromString,
                _registered_method=True)


class SmokerServiceServicer(object):
    """Service für den Smoker
    """

    def Notify(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SmokerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Notify': grpc.unary_unary_rpc_method_handler(
                    servicer.Notify,
                    request_deserializer=smokers__pb2.NotifyRequest.FromString,
                    response_serializer=smokers__pb2.NotifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'smokers.SmokerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('smokers.SmokerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SmokerService(object):
    """Service für den Smoker
    """

    @staticmethod
    def Notify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/smokers.SmokerService/Notify',
            smokers__pb2.NotifyRequest.SerializeToString,
            smokers__pb2.NotifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
